### ISSUE TITLE
import error when using with zope.sqlalchemy 1.2

### ISSUE THREAD

**Issue by wobsta** [zopefoundation/z3c.saconfig#9]
The recent update to zope.sqlalchemy 1.2 (see https://pypi.org/project/zope.sqlalchemy/#id1) renamed ZopeTransactionExtension to ZopeTransactionEvents. This breaks z3c.saconfig for me:

```python
>>> import z3c.saconfig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wobsta/plone/ev/dev/eggs/z3c.saconfig-0.15-py2.7.egg/z3c/saconfig/__init__.py", line 2, in <module>
    from z3c.saconfig.utility import (
  File "/home/wobsta/plone/ev/dev/eggs/z3c.saconfig-0.15-py2.7.egg/z3c/saconfig/utility.py", line 11, in <module>
    from zope.sqlalchemy import ZopeTransactionExtension
ImportError: cannot import name ZopeTransactionExtension
```

(Pinning zope.sqlalchemy to <= 1.1 helps for me at the moment.)

**Comment by mgedmin** [comment]
Background: sqlalchemy deprecated extensions in favour of event registrations.  zope.sqlalchemy 1.2 followed suit.  See https://github.com/zopefoundation/zope.sqlalchemy/pull/38/files for upgrade instructions.
